const express = require("express");
const route = express.Router();
const user = require("../controllers/userController");
const { auth } = require("../middleware/auth");
route.get("/all", auth, user.alluser);
route.post("/signin", auth,user.signin);
route.post("/signup", user.signup);
route.get("/search", auth, user.searchByName);
route.get("/me", auth, user.me);
module.exports = route;
